# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 00:40
from __future__ import unicode_literals

import chave.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande')], max_length=1, verbose_name='Tamanho')),
                ('timestamp', models.DateTimeField()),
                ('imagem', models.ImageField(upload_to=chave.models.foto_upload_path, verbose_name='Fotografia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
    ]
